[package]
name = "loopback"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true

[features]
default = ["client", "server"]
server = ["networking/server"]
client = ["networking/client"]

[dev-dependencies]
serde = "1.0"
test-log = "0.2"
