[package]
name = "loopback"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
bevy.workspace = true
networking.workspace = true

[features]
default = []
client = ["networking/client"]
server = ["networking/server"]
[dev-dependencies]
serde = "1.0"
test-log = "0.2"
