[package]
name = "forge_of_stories"
edition = { workspace = true }
version = { workspace = true }


[[bin]]
name = "forge_of_stories"
path = "src/client.rs"


[[bin]]
name = "forge_of_stories_server"
path = "src/server.rs"

[dependencies]
wizard = { workspace = true, optional = true }
illusion = { workspace = true, optional = true }


[features]
server = ["wizard"]
client = ["illusion"]
default = []
