[package]
name = "server"
version = "0.1.0"
edition = "2024"

# Dedicated Server Binary
[[bin]]
name = "server"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
app.workspace = true
shared = { workspace = true }
anyhow = { workspace = true }
settings = { workspace = true }
toml_edit = { workspace = true }
paths = { workspace = true }
time = { workspace = true }
bevy = { version = "0.16.1", default-features = false, features = [
    "std",
    "multi_threaded",
    "bevy_remote",
    "bevy_state",
    "bevy_log",
    "serialize",
] }

# --- Assets ---
toml = { workspace = true }
serde = { workspace = true }

# --- CLI ---
clap.workspace = true
color-eyre.workspace = true
crossterm.workspace = true
ratatui.workspace = true
tui-textarea = "0.7"

# --- Certificate ---
rustls = { workspace = true }
rcgen = { workspace = true }

# --- Server ---
quinn = { workspace = true }
tokio = { workspace = true }
# settings = { workspace = true }

[features]
default = ["dedicated_server"]
dedicated_server = []
local_server = []
